### ISSUE TITLE
fbpic not working with numba 0.43.0

### ISSUE THREAD

**Issue by delaossa** [fbpic/fbpic#345]
Hello Remi, Manuel and co., 
I have just started to play with FBPIC, but got a problem when trying to run one of the examples:

`[max-display001] /beegfs/desy/group/mpy/plasma/FBPIC/lwfa_example.fb $> python lwfa_script.py
Traceback (most recent call last):
[...]
AttributeError: module 'numba.findlib' has no attribute 'get_lib_dir'`

After downgrading numba from 0.43.0 to 0.41.0 (thanks Angel for suggesting this!), FBPIC run with no problems. 
I thought that it might be useful for others if I post it here. 

Thanks for sharing the code!

**Comment by RemiLehe** [comment]
Thanks a lot for letting us know!

I can reproduce the issue on my local machine.
(also: it seems that the issue only occurs when `pyculib` is installed ; both numba 0.41 and numba 0.42 work fine.)

@MKirchen : We could do a quick fix but doing something similar to PR #317 and do a new release, so that the users are not impacted. What do you think?
However, in the longer term, this might be tricky to fix. We could either try to fix `pyculib`, or switch to `cupy`, as recommended by the Numba team.

**Comment by RemiLehe** [comment]
Looks like the reason for the bug is that `numba` had a function `get_lib_dir` in version`0.42`:
https://github.com/numba/numba/blob/0.42.0/numba/findlib.py#L7
and replaced with `get_lib_dirs` in version `0.43`:
https://github.com/numba/numba/blob/0.43.0/numba/findlib.py#L7
So fixing it in `pyculib` would not be too difficult, but then I am not sure whether the fix would be uploaded to the standard distribution channels.

**Comment by MKirchen** [comment]
I think for the moment, we can apply the quick fix that you proposed.

**Comment by RemiLehe** [comment]
OK, there is now a new release (`0.12.0`) which aborts the code if `numba 0.43` is detected, and prompts the user to install `numba 0.42` instead.

**Comment by MKirchen** [comment]
This issue is resolved ( #356 ) by migrating from `pyculib` to `cupy`. Using `numba > 0.42` is possible starting with FBPIC release `0.13.0`.
